### ISSUE TITLE
Image compressor.py

### ISSUE THREAD

**Issue by Moddy2024** [meks-0202/Python-Tools#7]
I can provide a solution to an Image compressor tool. If you add the hacktoberfest label to it.

**Comment by meks-0202** [comment]
yes please, this repository already has the hacktoberfest tags

**Comment by Moddy2024** [comment]
> yes please, this repository already has the hacktoberfest tags

Ok Thank you. I will make a PR soon then

**Comment by Moddy2024** [comment]
Can you add the tag of hacktoberfest accepted.
Thank you.
